apiVersion: apps/v1
kind: Deployment
metadata:
  name: oehcsproducer-direct
  labels:
    app: oehcsproducer-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oehcsproducer-direct
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oehcsproducer-direct
    spec:
      containers:
      - image: javiermugueta/oehcsproducer-direct
        env:
        - name: OEHCS_CONNECTURL
          value: "130.61.86.204:6667,130.61.113.170:6667,130.61.47.254:6667,130.61.112.70:6667,130.61.87.248:6667"
        - name: TOPIC_NAME
          value: "MAINSTREAM"
        - name: NUM_PARTITIONS
          value: "10"
#        - name: DEBUG
#          value: "1"
        - name: MESSAGE
          value: "{\"updateId\" : NUMBER,\"store\" : NUMBER,\"section\" : NUMBER,\"changes\" :[{\"to\" : NUMBER,\"timestamp\": TIMESTAMP,\"items\": [{\"productCode\": NUMBER,\"model\": STRING,\"quality\": STRING,\"color\": STRING,\"size\": NUMBER,\"serialNumber\": NUMBER},{\"productCode\": NUMBER,\"model\": STRING,\"quality\": STRING,\"color\": STRING,\"size\": NUMBER,\"serialNumber\": NUMBER}]},{\"to\": NUMBER,\"timestamp\": TIMESTAMP,\"items\": [{\"productCode\": NUMBER,\"model\": STRING,\"quality\": STRING,\"color\": STRING,\"size\": NUMBER,\"serialNumber\": NUMBER}]}]}"
        name: oehcsproducer-direct